; You must register an 'Application at' https://dev.twitch.tv/console

[AUTH]
; Client ID from your application (Keep private)
ClientID = 
; Client Secret from your Application (Keep private)
ClientSecret = 
; Your channel name
TargetChannel = 

[MARKOV]
; Whether to train the text generator on the specified channel's chat
TrainOnChat = true
; Path to Ngram data (Automatically created if doesn't exist).
NgramPath = data.bin
; How to split the training text. 'word' OR 'character'
SplitStrategy = character 
; How many characters to split text by. Only used if SplitStrategy = character
CharacterCount = 4
; After how many messages to save Ngrams
AutosaveInterval = 50
; Command used to generate text (ignoring !)
GenerateCommand = mark
; Length of text to generate (Either words or 'CharacterCount' size chunks depending on. Not 100% sure though, it's magical)
LengthToGenerate = 100
; Whether to ignore StreamElements bot (for training)
IgnoreStreamElements = true
; How many times to try regenerating text without bad words before giving up
MaxRetries = 3