; You must register an 'Application at' https://dev.twitch.tv/console
; Settings marked with [R] are reloadable while the bot is running using !refreshconfig

[AUTH]
; Client ID from your application (Keep private)
ClientID = 
; Client Secret from your Application (Keep private)
ClientSecret = 
; Channel to run the bot on
TargetChannel = 
; Your name (to only allow the bot owner to run specific commands)
YourName = 

[MARKOV]
; [R] Whether to train the text generator on the specified channel's chat
TrainOnChat = true
; Path to Ngram data (Automatically created if doesn't exist).
NgramPath = data.pkl
; How to split the training text. 'word' OR 'character'
SplitStrategy = character 
; How many characters to split text by. Only used if SplitStrategy = character
CharacterCount = 4
; [R] After how many messages to save Ngrams
AutosaveInterval = 50
; Command used to generate text (ignoring !)
GenerateCommand = mark
; [R] Length of text to generate (Either words or 'CharacterCount' size chunks depending on. Not 100% sure though, it's magical)
LengthToGenerate = 200
; [R] How many times to try regenerating text without bad words before giving up
MaxRetries = 3
; [R] How many seconds to timeout the bot after a successful generation
MessageTimeout = 0

[TTS]
; [R] TTS toggle - Requires FFMPEG to be installed and added to PATH (I think)
TTS = true
; [R] TTS Language (language code 'lang' from https://gtts.readthedocs.io/en/latest/module.html#localized-accents)
TTSLanguage = en
; [R] TTS Top level domain ('tld' from https://gtts.readthedocs.io/en/latest/module.html#localized-accents)
TTSTLD = co.uk